##  Database  ##
spring:
  datasource:
    url: jdbc:postgresql://dpg-clp6vm946foc73cdk5cg-a/remo_9tb4
    username: remo
    password: d56ESQe9Wu0dzzEvP6JMqpuDragqR14E
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
application:
  port: 8090